import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import QueryClientProviderComponent from "@/providers/QueryClientProviderComponent";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className=" antialiased">
                <QueryClientProviderComponent>
                    <div className="flex flex-col min-h-screen justify-between">
                        <div>
                            <Header />
                            {children}
                        </div>
                        <Footer />
                    </div>
                </QueryClientProviderComponent>
            </body>
        </html>
    );
}
