import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["400", "700"],
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${lato.variable} antialiased`}>
                <div className="flex flex-col min-h-screen justify-between">
                    <div>
                        <Header />
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
